Set
c FAOcountries /
1   Armenia
2   Afghanistan
3   Albania
4   Algeria
7   Angola
8   Antigua and Barbuda
9   Argentina
10  Australia
11  Austria
12  Bahamas
13  Bahrain
14  Barbados
15  Belgium-Luxembourg
16  Bangladesh
18  Bhutan
19  Bolivia (Plurinational State of)
20  Botswana
21  Brazil
23  Belize
25  Solomon Islands
26  Brunei Darussalam
27  Bulgaria
28  Myanmar
29  Burundi
32  Cameroon
33  Canada
35  Cabo Verde
37  Central African Republic
38  Sri Lanka
39  Chad
40  Chile
41  China mainland
44  Colombia
45  Comoros
46  Congo
47  Cook Islands
48  Costa Rica
49  Cuba
50  Cyprus
51  Czechoslovakia
52  Azerbaijan
53  Benin
54  Denmark
55  Dominica
56  Dominican Republic
57  Belarus
58  Ecuador
59  Egypt
60  El Salvador
61  Equatorial Guinea
62  Ethiopia PDR
63  Estonia
66  Fiji
67  Finland
68  France
69  French Guiana
70  French Polynesia
73  Georgia
74  Gabon
75  Gambia
79  Germany
80  Bosnia and Herzegovina
81  Ghana
84  Greece
86  Grenada
87  Guadeloupe
89  Guatemala
90  Guinea
91  Guyana
93  Haiti
95  Honduras
96  China Hong Kong SAR
97  Hungary
98  Croatia
99  Iceland
100 India
101 Indonesia
102 Iran (Islamic Republic of)
103 Iraq
104 Ireland
105 Israel
106 Italy
107 Côte d'Ivoire
108 Kazakhstan
109 Jamaica
110 Japan
112 Jordan
113 Kyrgyzstan
114 Kenya
115 Cambodia
116 Democratic People's Republic of Korea
117 Republic of Korea
118 Kuwait
119 Latvia
120 Lao People's Democratic Republic
121 Lebanon
122 Lesotho
123 Liberia
124 Libya
126 Lithuania
129 Madagascar
130 Malawi
131 Malaysia
132 Maldives
133 Mali
134 Malta
135 Martinique
136 Mauritania
137 Mauritius
138 Mexico
141 Mongolia
143 Morocco
144 Mozambique
146 Republic of Moldova
147 Namibia
149 Nepal
150 Netherlands (Kingdom of the)
151 Netherlands Antilles (former)
153 New Caledonia
154 North Macedonia
155 Vanuatu
156 New Zealand
157 Nicaragua
158 Niger
159 Nigeria
162 Norway
165 Pakistan
166 Panama
167 Czechia
168 Papua New Guinea
169 Paraguay
170 Peru
171 Philippines
173 Poland
174 Portugal
175 Guinea-Bissau
176 Timor-Leste
177 Puerto Rico
178 Eritrea
179 Qatar
181 Zimbabwe
182 Réunion
183 Romania
184 Rwanda
185 Russian Federation
186 Serbia and Montenegro
188 Saint Kitts and Nevis
189 Saint Lucia
191 Saint Vincent and the Grenadines
193 Sao Tome and Principe
194 Saudi Arabia
195 Senegal
196 Seychelles
197 Sierra Leone
198 Slovenia
199 Slovakia
200 Singapore
201 Somalia
202 South Africa
203 Spain
206 Sudan (former)
207 Suriname
208 Tajikistan
209 Eswatini
210 Sweden
211 Switzerland
212 Syrian Arab Republic
213 Turkmenistan
215 United Republic of Tanzania
216 Thailand
217 Togo
219 Tonga
220 Trinidad and Tobago
221 Oman
222 Tunisia
223 Türkiye
226 Uganda
228 USSR
229 United Kingdom of Great Britain and Northern Ireland
230 Ukraine
231 United States of America
233 Burkina Faso
234 Uruguay
235 Uzbekistan
236 Venezuela (Bolivarian Republic of)
237 Viet Nam
238 Ethiopia
244 Samoa
248 Yugoslav SFR
249 Yemen
250 Democratic Republic of the Congo
251 Zambia
255 Belgium
256 Luxembourg
272 Serbia
276 Sudan
277 South Sudan
299 Palestine
351 China

/

map_c_i(c,i)  mapping between FAO countries (c) and FAO regions (i)
/
1.145
2.34
3.39
4.15
7.17
8.29
9.5
10.53
11.155
12.29
13.145
14.29
15.155
16.34
18.34
19.5
20.18
21.5
23.13
25.54
26.35
27.151
28.35
29.14
32.17
33.21
35.11
37.17
38.34
39.17
40.5
41.30
44.5
45.14
46.17
47.61
48.13
49.29
50.145
51.151
52.145
53.11
54.154
55.29
56.29
57.151
58.5
59.15
60.13
61.17
62.14
63.154
66.54
67.154
68.155
69.5
70.61
73.145
74.17
75.11
79.155
80.39
81.11
84.39
86.29
87.29
89.13
90.11
91.5
93.29
95.13
96.30
97.151
98.39
99.154
100.34
101.35
102.34
103.145
104.154
105.145
106.39
107.11
108.143
109.29
110.30
112.145
113.143
114.14
115.35
116.30
117.30
118.145
119.154
120.35
121.145
122.18
123.11
124.15
126.154
129.14
130.14
131.35
132.34
133.11
134.39
135.29
136.11
137.14
138.13
141.30
143.15
144.14
146.151
147.18
149.34
150.155
151.29
153.54
154.39
155.54
156.53
157.13
158.11
159.11
162.154
165.34
166.13
167.151
168.54
169.5
170.5
171.35
173.151
174.39
175.11
176.35
177.29
178.14
179.145
181.14
182.14
183.151
184.14
185.151
186.39
188.29
189.29
191.29
193.17
194.145
195.11
196.14
197.11
198.39
199.151
200.35
201.14
202.18
203.39
206.15
207.5
208.143
209.18
210.154
211.155
212.145
213.143
215.14
216.35
217.11
219.61
220.29
221.145
222.15
223.145
226.14
228.151
229.154
230.151
231.21
233.11
234.5
235.143
236.5
237.35
238.14
244.61
248.39
249.145
250.17
251.14
255.155
256.155
272.39
276.15
277.14
299.145
351.30
/

k  -- FAO item list of produced food items (food items for which production and price data exist - excludes processed items)
/
15  Wheat
27  Rice
30  MilledRice
44  Barley
51  Beerofbarleymalted
56  Maize(corn)
60  Oilofmaize
71  Rye
75  Oats
79  Millet
83  Sorghum
89  Buckwheat
92  Quinoa
94  Fonio
97  Triticale
101 Canaryseed
103 Mixedgrain
108 Cerealsnec
116 Potatoes
122 Sweetpotatoes
125 Cassavafresh
135 Yautia
136 Taro
137 Yams
149 Ediblerootsandtuberswithhighstarchorinulincontentnecfresh
156 Sugarcane
157 Sugarbeet
161 Othersugarcropsnec
162 Rawcaneorbeetsugar(centrifugalonly)
165 Molasses
176 Beansdry
181 Broadbeansandhorsebeansdry
187 Peasdry
191 Chickpeasdry
195 Cowpeasdry
197 Pigeonpeasdry
201 Lentilsdry
203 Bambarabeansdry
205 Vetches
210 Lupins
211 Otherpulsesnec
216 Brazilnutsinshell
217 Cashewnutsinshell
220 Chestnutsinshell
221 Almondsinshell
222 Walnutsinshell
223 Pistachiosinshell
224 Kolanuts
225 Hazelnutsinshell
226 Arecanuts
234 Othernuts(excludingwildediblenutsandgroundnuts)inshellnec
236 Soyabeans
237 Soyabeanoil
242 Groundnutsexcludingshelled
244 Groundnutoil
249 Coconutsinshell
252 Coconutoil
254 Oilpalmfruit
256 Palmkernels
257 Palmoil
258 Oilofpalmkernel
260 Olives
261 Oliveoil
263 Karitenuts(sheanuts)
265 Castoroilseeds
267 Sunflowerseed
268 Sunflower-seedoilcrude
270 Rapeorcolzaseed
271 Rapeseedorcanolaoilcrude
275 Tungnuts
277 Jojobaseeds
280 Safflowerseed
281 Safflower-seedoilcrude
289 Sesameseed
290 Oilofsesameseed
292 Mustardseed
296 Poppyseed
299 Melonseed
305 Tallowtreeseeds
310 Kapokfruit
311 Kapokseedinshell
328 Seedcottonunginned
329 Cottonseed
331 Cottonseedoil
333 Linseed
334 Oiloflinseed
336 Hempseed
339 Otheroilseedsnec
358 Cabbages
366 Artichokes
367 Asparagus
372 Lettuceandchicory
373 Spinach
378 Cassavaleaves
388 Tomatoes
393 Cauliflowersandbroccoli
394 Pumpkinssquashandgourds
397 Cucumbersandgherkins
399 Eggplants(aubergines)
401 Chilliesandpeppersgreen(CapsicumsppandPimentaspp)
402 Onionsandshallotsgreen
403 Onionsandshallotsdry(excludingdehydrated)
406 Greengarlic
407 Leeksandotheralliaceousvegetables
414 Otherbeansgreen
417 Peasgreen
420 Broadbeansandhorsebeansgreen
423 Stringbeans
426 Carrotsandturnips
430 Okra
446 Greencorn(maize)
449 Mushroomsandtruffles
459 Chicoryroots
461 Locustbeans(carobs)
463 Othervegetablesfreshnec
484 Bananascavendish
485 OtherBanana
486 Bananas
487 Plantains
488 CookingBananas
489 Plantainsandcookingbananas
490 Oranges
495 Tangerinesmandarinsclementines
497 Lemonsandlimes
507 Pomelosandgrapefruits
512 Othercitrusfruitnec
515 Apples
521 Pears
523 Quinces
526 Apricots
530 Sourcherries
531 Cherries
534 Peachesandnectarines
536 Plumsandsloes
541 Otherstonefruits
542 Otherpomefruits
544 Strawberries
547 Raspberries
549 Gooseberries
550 Currants
552 Blueberries
554 Cranberries
558 Otherberriesandfruitsofthegenusvacciniumnec
560 Grapes
564 Wine
567 Watermelons
568 Cantaloupesandothermelons
569 Figs
571 Mangoesguavasandmangosteens
572 Avocados
574 Pineapples
577 Dates
587 Persimmons
591 Cashewapple
592 Kiwifruit
600 Papayas
603 Othertropicalfruitsnec
619 Otherfruitsnec
656 Coffeegreen
661 Cocoabeans
667 Tealeaves
671 Matéleaves
675 Greentea(notfermented)blacktea(fermented)andpartlyfermentedteainimmediatepackingsofacontentnotexceeding3kg
677 Hopcones
687 Pepper(Piperspp)raw
689 Chilliesandpeppersdry(CapsicumsppPimentaspp)raw
692 Vanillaraw
693 Cinnamonandcinnamon-treeflowersraw
698 Cloves(wholestems)raw
702 Nutmegmacecardamomsraw
711 Anisebadiancoriandercumincarawayfennelandjuniperberriesraw
720 Gingerraw
723 Otherstimulantspiceandaromaticcropsnec
748 Peppermintspearmint
754 Pyrethrumdriedflowers
767 Cottonlintginned
771 Flaxraworretted
773 FlaxProcessed
777 Truehempraworretted
778 Kapokfibreraw
780 Juteraworretted
782 Kenafandothertextilebastfibresraworretted
788 Ramieraworretted
789 Sisalraw
800 Agavefibresrawnec
809 Abacamanilahempraw
813 Coirraw
821 Otherfibrecropsrawnec
826 Unmanufacturedtobacco
836 Naturalrubberinprimaryforms
839 Balatagutta-perchaguayulechicleandsimilarnaturalgumsinprimaryformsorinplatessheetsorstrip
866 Cattle
867 Meatofcattlewiththebonefreshorchilled
868 Edibleoffalofcattlefreshchilledorfrozen
869 Cattlefatunrendered
882 Rawmilkofcattle
885 Creamfresh
886 Butterofcowmilk
887 Gheefromcowmilk
888 Skimmilkofcows
889 Wholemilkcondensed
890 Wheycondensed
891 Yoghurt
894 Wholemilkevaporated
895 Skimmilkevaporated
896 Skimmilkcondensed
897 Wholemilkpowder
898 Skimmilkandwheypowder
899 Buttermilkdry
900 Wheydry
901 Cheesefromwholecowmilk
904 Cheesefromskimmedcowmilk
919 Rawhidesandskinsofcattle
945 MeatofCattlewithBone
946 Buffalo
947 Meatofbuffalofreshorchilled
948 Edibleoffalofbuffalofreshchilledorfrozen
949 Buffalofatunrendered
951 Rawmilkofbuffalo
952 Butterofbuffalomilk
953 Gheefrombuffalomilk
955 Cheesefrommilkofbuffalofreshorprocessed
957 Rawhidesandskinsofbuffaloes
973 BuffaloMeat
976 Sheep
977 Meatofsheepfreshorchilled
978 Edibleoffalofsheepfreshchilledorfrozen
979 Sheepfatunrendered
982 Rawmilkofsheep
983 Butterandgheeofsheepmilk
984 Cheesefrommilkofsheepfreshorprocessed
987 Shornwoolgreasyincludingfleece-washedshornwool
995 Rawhidesandskinsofsheeporlambs
1013    SomeKindOfMeat
1016    Goats
1017    Meatofgoatfreshorchilled
1018    Edibleoffalofgoatfreshchilledorfrozen
1019    Goatfatunrendered
1020    Rawmilkofgoats
1021    Cheesefrommilkofgoatsfreshorprocessed
1022    Butterofgoatmilk
1025    Rawhidesandskinsofgoatsorkids
1033    SomeKindOfMeat
1034    Swinepigs
1035    Meatofpigwiththebonefreshorchilled
1036    Edibleoffalofpigsfreshchilledorfrozen
1037    Fatofpigs
1043    Pigfatrendered
1056    SomeKindOfMeat
1057    Chickens
1058    Meatofchickensfreshorchilled
1062    Heneggsinshellfresh
1068    Ducks
1069    Meatofducksfreshorchilled
1071    SomeKindOfMeat
1072    Geese
1073    Meatofgeesefreshorchilled
1078    SomeKindOfMeat
1079    Turkeys
1080    Meatofturkeysfreshorchilled
1083    Otherbirds
1085    SomeKindOfMeat
1088    SomeKindOfMeat
1089    Meatofpigeonsandotherbirdsnecfreshchilledorfrozen
1091    Eggsfromotherbirdsinshellfreshnec
1095    SomeKindOfMeat
1096    Horses
1097    Horsemeatfreshorchilled
1098    Edibleoffalsofhorsesandotherequinesfreshchilledorfrozen
1107    Asses
1108    Meatofassesfreshorchilled
1110    Mulesandhinnies
1111    Meatofmulesfreshorchilled
1121    SomeKindOfMeat
1123    SomeKindOfMeat
1125    SomeKindOfMeat
1126    Camels
1127    Meatofcamelsfreshorchilled
1128    Edibleoffalsofcamelsandothercamelidsfreshchilledorfrozen
1129    Fatofcamels
1130    Rawmilkofcamel
1138    SomeKindOfMeat
1140    Rabbitsandhares
1141    Meatofrabbitsandharesfreshorchilled
1145    SomeKindOfMeat
1150    Otherrodents
1151    Meatofotherdomesticrodentsfreshorchilled
1157    Othercamelids
1158    Meatofotherdomesticcamelidsfreshorchilled
1163    Gamemeatfreshchilledorfrozen
1166    Othermeatnec(excludingmammals)freshchilledorfrozen
1176    Snailsfreshchilledfrozendriedsaltedorinbrineexceptseasnails
1181    Bees
1182    Naturalhoney
1183    Beeswax
1185    Silk-wormcocoonssuitableforreeling
1186    Rawsilk(notthrown)
1225    Tallow
1242    Margarineandshortening
1717    Cerealsprimary
1720    RootsandTubersTotal
1723    SugarCropsPrimary
1726    PulsesTotal
1729    TreenutsTotal
1732    OilcropsOilEquivalent
1735    VegetablesPrimary
1738    FruitPrimary
1745    Cheese(AllKinds)
1746    CattleandBuffaloes
1749    SheepandGoats
1765    MeatTotal
1780    MilkTotal
1783    EggsPrimary
1804    CitrusFruitTotal
1806    BeefandBuffaloMeatprimary
1807    SheepandGoatMeat
1808    MeatPoultry
1809    SkimMilk&ButtermilkDry
1811    ButterandGhee
1816    Evaporated&CondensedMilk
1841    OilcropsCakeEquivalent
2029    PoultryBirds
17530   FibreCropsFibreEquivalent
*   
/

j Sorted FAO items incl. processed items (completed for missing items that are recorded in trade)
/
15  Wheat
**-**
16 Wheat and meslin flour
17 Bran of Wheat
18 Uncooked pasta not stuffed or otherwise prepared
19 Germ of wheat
20 Bread
21  Bulgur
22  Pastry

27  Rice
**-**
28  Husked rice
29  Rice milled (husked)
30  Rice paddy (rice milled equivalent)
31  Rice milled
32  Rice broken
35  Bran of rice
36  Oil of rice bran
37  Cake of rice bran
38  Flour of rice
39  Rice-fermented beverages
41  Breakfast cereals


44  Barley
**-**
45  Pot barley
46  Barley pearled
47  Bran of barley
48  Barley flour and grits
49  Malt whether or not roasted
50  Malt extract

51  Beerofbarleymalted
56  Maize(corn)
**-**
57  Germ of maize
58  Flour of maize
59  Bran of maize

60  Oilofmaize
**-**
61  Cake of maize

71  Rye
**-**
72 Flour of rye
73  Bran of rye

75  Oats
**-**
76  Oats rolled

79  Millet
**-**
80  Flour of millet
81  Bran of millet

83  Sorghum
**-**
84  Flour of sorghum

85  Bran of sorghum
**-**
86  Beer of sorghum malted

89  Buckwheat
**-**
90  Flour of buckwheat
91  Bran of buckwheat

92  Quinoa
94  Fonio
**-**
95  Flour of fonio
96  Bran of fonio

97  Triticale
101 Canaryseed
103 Mixedgrain
**-**
104 Flour of mixed grain
105 Bran of mixed grain


108 Cerealsnec
**-**
109 Infant food
110 Communion wafers empty cachets of a kind suitable for pharmaceutical use sealing wafers rice paper and similar products.
111 Flour of cereals n.e.c.
112 Bran of cereals n.e.c.
113 Cereal preparations
114 Mixes and doughs for the preparation of bakers' wares
115 Food preparations of flour meal or malt extract

116 Potatoes
**-**
117 Flour meal powder flakes granules and pellets of potatoes
118 Potatoes frozen
120 Potato offals
121 Tapioca of potatoes

122 Sweetpotatoes
125 Cassavafresh
**-**
126 Flour of cassava
127 Tapioca of cassava
128 Cassava dry
129 Starch of cassava

135 Yautia
136 Taro
137 Yams
149 Ediblerootsandtuberswithhighstarchorinulincontentnecfresh
**-**
150 Flour of roots and tubers n.e.c.
151 Edible roots and tubers with high starch or inulin content n.e.c dry

156 Sugarcane
157 Sugarbeet
**-**
160 Refined cane or beet sugar in solid form containing added flavouring or colouring matter; maple sugar and maple syrup

161 Othersugarcropsnec
162 Rawcaneorbeetsugar(centrifugalonly)
**-**
163 Cane sugar non-centrifugal
164 Refined sugar

165 Molasses
**-**
166 Other fructose and syrup
167 Sugar and syrups n.e.c.
168 Sugar confectionery
169 Beet pulp
170 Bagasse
172 Glucose and dextrose
173 Lactose
175 Isoglucose

176 Beansdry
181 Broadbeansandhorsebeansdry
187 Peasdry
191 Chickpeasdry
195 Cowpeasdry
197 Pigeonpeasdry
201 Lentilsdry
203 Bambarabeansdry
205 Vetches
210 Lupins
**-**
211 Otherpulsesnec
212 Flour of pulses
213 Bran of pulses

216 Brazilnutsinshell
217 Cashewnutsinshell
220 Chestnutsinshell
221 Almondsinshell
222 Walnutsinshell
223 Pistachiosinshell
224 Kolanuts
225 Hazelnutsinshell
226 Arecanuts
**-**
229 Brazil nuts shelled
230 Cashew nuts shelled
231 Almonds shelled
232 Walnuts shelled
233 Hazelnuts shelled

234 Othernuts(excludingwildediblenutsandgroundnuts)inshellnec
**-**
235 Prepared nuts

236 Soyabeans
237 Soyabeanoil
**-**
238 Cake of  soya beans
239 Soya sauce
240 Soya paste

242 Groundnutsexcludingshelled
**-**
243 Groundnuts shelled
245 Cake of groundnuts
246 Prepared groundnuts
247 Peanut butter
250 Coconuts desiccated
251 Copra
253 Cake of copra
259 Cake of palm kernel
262 Olives preserved
264 Butter of karite nuts
266 Oil of castor beans
269 Cake of sunflower seed
272 Cake of rapeseed
273 Olive residues
274 Oil of olive residues
276 Oil of tung nuts
278 Jojoba oil
282 Cake of safflowerseed
291 Cake of sesame seed
293 Mustard seed oil crude
294 Cake of mustard seed
295 Flour of mustard seed
297 Oil of poppy seed
306 Vegetable tallow
311 Kapokseed in shell
312 Kapokseed shelled
313 Oil of kapok
314 Cake of kapok
332 Cake of cottonseed
335 Cake of  linseed
338 Cake of hempseed
340 Other oil of vegetable origin crude n.e.c.
341 Cake oilseeds nes
343 Flours and meals of oil seeds or oleaginous fruits except those of mustard

244 Groundnutoil
249 Coconutsinshell
252 Coconutoil
254 Oilpalmfruit
256 Palmkernels
257 Palmoil
258 Oilofpalmkernel
260 Olives
261 Oliveoil
263 Karitenuts(sheanuts)
265 Castoroilseeds
267 Sunflowerseed
268 Sunflower-seedoilcrude
270 Rapeorcolzaseed
271 Rapeseedorcanolaoilcrude
275 Tungnuts
277 Jojobaseeds
280 Safflowerseed
281 Safflower-seedoilcrude
289 Sesameseed
290 Oilofsesameseed
292 Mustardseed
296 Poppyseed
299 Melonseed
305 Tallowtreeseeds
310 Kapokfruit
328 Seedcottonunginned
329 Cottonseed
331 Cottonseedoil
333 Linseed
334 Oiloflinseed
336 Hempseed
339 Otheroilseedsnec


358 Cabbages
366 Artichokes
367 Asparagus
372 Lettuceandchicory
373 Spinach
378 Cassavaleaves
388 Tomatoes
**-**
390 Tomato juice
391 Paste of tomatoes
392 Tomatoes peeled (ot vinegar)

393 Cauliflowersandbroccoli
394 Pumpkinssquashandgourds
397 Cucumbersandgherkins
399 Eggplants(aubergines)
401 Chilliesandpeppersgreen(CapsicumsppandPimentaspp)
402 Onionsandshallotsgreen
403 Onionsandshallotsdry(excludingdehydrated)
406 Greengarlic
407 Leeksandotheralliaceousvegetables
414 Otherbeansgreen
417 Peasgreen
420 Broadbeansandhorsebeansgreen
423 Stringbeans
426 Carrotsandturnips
430 Okra
446 Greencorn(maize)
**-**
447 Sweet corn frozen
448 Sweet corn prepared or preserved

449 Mushroomsandtruffles
**-**
450 Dried mushrooms
451 Canned mushrooms
460 Vegetable products fresh or dry n.e.c.
466 Other vegetable juices
469 Vegetables dehydrated
471 Vegetables pulses and potatoes preserved by vinegar or acetic acid
472 Vegetables preserved nes (ot vinegar)
473 Vegetables frozen
474 Other vegetables provisionally preserved
475 Vegetables preserved (frozen)
476 Homogenized vegetable preparations


459 Chicoryroots
461 Locustbeans(carobs)
463 Othervegetablesfreshnec
484 Bananascavendish
485 OtherBanana
486 Bananas
487 Plantains
488 CookingBananas
489 Plantainsandcookingbananas
490 Oranges
**-**
491 Orange juice
492 Orange juice concentrated
496 Juice of tangerine
498 Juice of lemon
499 Lemon juice concentrated

495 Tangerinesmandarinsclementines
497 Lemonsandlimes
507 Pomelosandgrapefruits
**-**
509 Grapefruit juice
510 Grapefruit juice concentrated
513 Juice of citrus fruit n.e.c.
514 Citrus juice concentrated n.e.c.

512 Othercitrusfruitnec

515 Apples
**-**
517 Cider and other fermented beverages
518 Apple juice
519 Apple juice concentrated
527 Apricots dried
537 Plums dried
538 Juice of plum
539 Juice of plum concentrated

521 Pears
523 Quinces
526 Apricots
530 Sourcherries
531 Cherries
534 Peachesandnectarines
536 Plumsandsloes
541 Otherstonefruits
542 Otherpomefruits
544 Strawberries
547 Raspberries
549 Gooseberries
550 Currants
552 Blueberries
554 Cranberries
558 Otherberriesandfruitsofthegenusvacciniumnec
560 Grapes
**-**
561 Raisins
562 Grape juice
563 Must of grape

564 Wine
**-**
565 Vermouth and other wine of fresh grapes flavoured with plats or aromatic substances
566 Grapes marc

567 Watermelons
568 Cantaloupesandothermelons
569 Figs
**-**
570 Figs dried

580 Juice of pineapples concentrated

571 Mangoesguavasandmangosteens
**-**
583 Juice of mango
584 Mango pulp

572 Avocados
574 Pineapples
**-**
575 Pineapples otherwise prepared or preserved
576 Pineapple juice

577 Dates
587 Persimmons
591 Cashewapple
592 Kiwifruit
600 Papayas
603 Othertropicalfruitsnec
**-**
604 Other tropical fruit dried
620 Other fruit n.e.c. dried
622 Juice of fruits n.e.c.
623 Fruit prepared n.e.c.
624 Flour of fruits
625 Fruit nuts peel sugar preserved
626 Homogenized cooked fruit prepared
628 Pulp waste of fruit for feed
630 Cane tops
631 Ice and snow
633 Other non-alcoholic caloric beverages
634 Undenatured ethyl alcohol of an alcoholic strength by volume of less than 80% vol; spirits liqueurs and other spirituous beverages
635 Cereal straw husks unprepared ground pressed or in the form of pellets
636 Forage and silage maize
639 Other grasses for forage
640 Clover for forage
641 Forage and silage alfalfa
643 Other legumes for forage
646 Turnips for forage
647 Beets for fodder
649 Swedes for fodder
651 Other forage products n.e.c.
652 Vegetable products for feed n.e.c.
653 Food wastes
654 Brewing or distilling dregs and waste
655 Vegetables and roots fodder

619 Otherfruitsnec
656 Coffeegreen
**-**
657 Coffee decaffeinated or roasted
658 Coffee substitutes
659 Coffee extracts
660 Coffee husks and skins

661 Cocoabeans
**-**
662 Cocoa paste not defatted
663 Cocoa husks and shells
664 Cocoa butter fat and oil
665 Cocoa powder and cake
666 Chocolate products nes

667 Tealeaves
671 Matéleaves
**-**
672 Extracts essences and concentrates of tea or mate and preparations with a basis thereof or with a basis of tea or maté

675 Greentea(notfermented)blacktea(fermented)andpartlyfermentedteainimmediatepackingsofacontentnotexceeding3kg
677 Hopcones
687 Pepper(Piperspp)raw
689 Chilliesandpeppersdry(CapsicumsppPimentaspp)raw
692 Vanillaraw
693 Cinnamonandcinnamon-treeflowersraw
698 Cloves(wholestems)raw
702 Nutmegmacecardamomsraw
711 Anisebadiancoriandercumincarawayfennelandjuniperberriesraw
720 Gingerraw
723 Otherstimulantspiceandaromaticcropsnec
**-**
737 Oil of citronella
753 Essential oils n.e.c.
755 Pyrethrum extract
768 Cotton carded or combed
769 Cotton waste
770 Cotton linters
774 Flax tow and waste

748 Peppermintspearmint
754 Pyrethrumdriedflowers
767 Cottonlintginned
771 Flaxraworretted
773 FlaxProcessed
777 Truehempraworretted
778 Kapokfibreraw
780 Juteraworretted
782 Kenafandothertextilebastfibresraworretted
788 Ramieraworretted
789 Sisalraw
800 Agavefibresrawnec
809 Abacamanilahempraw
813 Coirraw
821 Otherfibrecropsrawnec
826 Unmanufacturedtobacco
**-**
828 Cigarettes
829 Cigars and cheroots
831 Other manufactured tobacco and manufactured tobacco substitutes;"homogenized" or "reconstituted" tobacco; tobacco extracts and essences

836 Naturalrubberinprimaryforms
**-**
837 Natural rubber in other forms

839 Balatagutta-perchaguayulechicleandsimilarnaturalgumsinprimaryformsorinplatessheetsorstrip
**-**
840 Feed compound cattle
841 Feed compound poultry
842 Feed compound pigs
843 Dog or cat food put up for retail sale
845 Compound feed n.e.c.
846 Gluten feed and meal
850 Feed supplements
852 Feed other concentrates nes
853 Vitamins
855 Feed minerals
857 Hay non-leguminous
858 Hay for forage from legumes
859 Hay for forage from other crops n.e.c.
862 Lucerne (alfalfa) meal and pellets

866 Cattle
867 Meatofcattlewiththebonefreshorchilled
868 Edibleoffalofcattlefreshchilledorfrozen
869 Cattlefatunrendered
882 Rawmilkofcattle
885 Creamfresh
886 Butterofcowmilk
887 Gheefromcowmilk
888 Skimmilkofcows
889 Wholemilkcondensed
890 Wheycondensed
891 Yoghurt
894 Wholemilkevaporated
895 Skimmilkevaporated
896 Skimmilkcondensed
897 Wholemilkpowder
898 Skimmilkandwheypowder
899 Buttermilkdry
900 Wheydry
901 Cheesefromwholecowmilk
904 Cheesefromskimmedcowmilk
919 Rawhidesandskinsofcattle
945 MeatofCattlewithBone
946 Buffalo
947 Meatofbuffalofreshorchilled
948 Edibleoffalofbuffalofreshchilledorfrozen
949 Buffalofatunrendered
951 Rawmilkofbuffalo
952 Butterofbuffalomilk
953 Gheefrombuffalomilk
955 Cheesefrommilkofbuffalofreshorprocessed
957 Rawhidesandskinsofbuffaloes
973 BuffaloMeat
976 Sheep
977 Meatofsheepfreshorchilled
978 Edibleoffalofsheepfreshchilledorfrozen
979 Sheepfatunrendered
982 Rawmilkofsheep
983 Butterandgheeofsheepmilk
984 Cheesefrommilkofsheepfreshorprocessed
987 Shornwoolgreasyincludingfleece-washedshornwool
995 Rawhidesandskinsofsheeporlambs
1013  SomeKindOfMeat
1016  Goats
1017  Meatofgoatfreshorchilled
1018  Edibleoffalofgoatfreshchilledorfrozen
1019  Goatfatunrendered
1020  Rawmilkofgoats
1021  Cheesefrommilkofgoatsfreshorprocessed
1022  Butterofgoatmilk
1025  Rawhidesandskinsofgoatsorkids
1033  SomeKindOfMeat
1034   Swinepigs
1035    Meatofpigwiththebonefreshorchilled
1036    Edibleoffalofpigsfreshchilledorfrozen
1037    Fatofpigs
1043    Pigfatrendered
1056    SomeKindOfMeat
1057    Chickens
1058    Meatofchickensfreshorchilled
1062    Heneggsinshellfresh
1068    Ducks
1069    Meatofducksfreshorchilled
1071    SomeKindOfMeat
1072    Geese
1073    Meatofgeesefreshorchilled
1078    SomeKindOfMeat
1079    Turkeys
1080    Meatofturkeysfreshorchilled
1083    Otherbirds
1085    SomeKindOfMeat
1088    SomeKindOfMeat
1089    Meatofpigeonsandotherbirdsnecfreshchilledorfrozen
1091    Eggsfromotherbirdsinshellfreshnec
1095    SomeKindOfMeat
1096    Horses
1097    Horsemeatfreshorchilled
1098    Edibleoffalsofhorsesandotherequinesfreshchilledorfrozen
1107    Asses
1108    Meatofassesfreshorchilled
1110    Mulesandhinnies
1111    Meatofmulesfreshorchilled
1121    SomeKindOfMeat
1123    SomeKindOfMeat
1125    SomeKindOfMeat
1126    Camels
1127    Meatofcamelsfreshorchilled
1128    Edibleoffalsofcamelsandothercamelidsfreshchilledorfrozen
1129    Fatofcamels
1130    Rawmilkofcamel
1138    SomeKindOfMeat
1140    Rabbitsandhares
1141    Meatofrabbitsandharesfreshorchilled
1145    SomeKindOfMeat
1150    Otherrodents
1151    Meatofotherdomesticrodentsfreshorchilled
1157    Othercamelids
1158    Meatofotherdomesticcamelidsfreshorchilled
1163    Gamemeatfreshchilledorfrozen
1166    Othermeatnec(excludingmammals)freshchilledorfrozen
1176    Snailsfreshchilledfrozendriedsaltedorinbrineexceptseasnails
1181    Bees
1182    Naturalhoney
1183    Beeswax
1185    Silk-wormcocoonssuitableforreeling
1186    Rawsilk(notthrown)
1225    Tallow
1242    Margarineandshortening
1717    Cerealsprimary
1720    RootsandTubersTotal
1723    SugarCropsPrimary
1726    PulsesTotal
1729    TreenutsTotal
1732    OilcropsOilEquivalent
1735    VegetablesPrimary
1738    FruitPrimary
1745    Cheese(AllKinds)
1746    CattleandBuffaloes
1749    SheepandGoats
1765    MeatTotal
1780    MilkTotal
1783    EggsPrimary
1804    CitrusFruitTotal
1806    BeefandBuffaloMeatprimary
1807    SheepandGoatMeat
1808    MeatPoultry
1809    SkimMilk&ButtermilkDry
1811    ButterandGhee
1816    Evaporated&CondensedMilk
1841    OilcropsCakeEquivalent
2029    PoultryBirds
17530   FibreCropsFibreEquivalent
**** unspecified non-crop items
870
871
872
873
874
875
877
878
892
893
903
905
907
908
909
910
920
921
922
928
929
930
958
959
988
994
996
997
998
999
1002
1007
1008
1009
1026
1030
1031
1038
1039
1040
1041
1042
1045
1047
1059
1060
1061
1063
1064
1065
1066
1074
1075
1100
1103
1104
1105
1134
1136
1146
1164
1167
1168
1171
1172
1173
1187
1195
1214
1215
1216
1217
1218
1219
1221
1222
1232
1241
1243
1259
1274
1275
1276
1277
1293
1295
1296
/

kcrop(k)  Only food crops - excl. processed
/
15  Wheat
27  Rice
30  MilledRice
44  Barley
51  Beerofbarleymalted
56  Maize(corn)
60  Oilofmaize
71  Rye
75  Oats
79  Millet
83  Sorghum
89  Buckwheat
92  Quinoa
94  Fonio
97  Triticale
101 Canaryseed
103 Mixedgrain
108 Cerealsnec
116 Potatoes
122 Sweetpotatoes
125 Cassavafresh
135 Yautia
136 Taro
137 Yams
149 Ediblerootsandtuberswithhighstarchorinulincontentnecfresh
156 Sugarcane
157 Sugarbeet
161 Othersugarcropsnec
162 Rawcaneorbeetsugar(centrifugalonly)
165 Molasses
176 Beansdry
181 Broadbeansandhorsebeansdry
187 Peasdry
191 Chickpeasdry
195 Cowpeasdry
197 Pigeonpeasdry
201 Lentilsdry
203 Bambarabeansdry
205 Vetches
210 Lupins
211 Otherpulsesnec
216 Brazilnutsinshell
217 Cashewnutsinshell
220 Chestnutsinshell
221 Almondsinshell
222 Walnutsinshell
223 Pistachiosinshell
224 Kolanuts
225 Hazelnutsinshell
226 Arecanuts
234 Othernuts(excludingwildediblenutsandgroundnuts)inshellnec
236 Soyabeans
237 Soyabeanoil
242 Groundnutsexcludingshelled
244 Groundnutoil
249 Coconutsinshell
252 Coconutoil
254 Oilpalmfruit
256 Palmkernels
257 Palmoil
258 Oilofpalmkernel
260 Olives
261 Oliveoil
263 Karitenuts(sheanuts)
265 Castoroilseeds
267 Sunflowerseed
268 Sunflower-seedoilcrude
270 Rapeorcolzaseed
271 Rapeseedorcanolaoilcrude
275 Tungnuts
277 Jojobaseeds
280 Safflowerseed
281 Safflower-seedoilcrude
289 Sesameseed
290 Oilofsesameseed
292 Mustardseed
296 Poppyseed
299 Melonseed
305 Tallowtreeseeds
310 Kapokfruit
311 Kapokseedinshell
328 Seedcottonunginned
329 Cottonseed
331 Cottonseedoil
333 Linseed
334 Oiloflinseed
336 Hempseed
339 Otheroilseedsnec
358 Cabbages
366 Artichokes
367 Asparagus
372 Lettuceandchicory
373 Spinach
378 Cassavaleaves
388 Tomatoes
393 Cauliflowersandbroccoli
394 Pumpkinssquashandgourds
397 Cucumbersandgherkins
399 Eggplants(aubergines)
401 Chilliesandpeppersgreen(CapsicumsppandPimentaspp)
402 Onionsandshallotsgreen
403 Onionsandshallotsdry(excludingdehydrated)
406 Greengarlic
407 Leeksandotheralliaceousvegetables
414 Otherbeansgreen
417 Peasgreen
420 Broadbeansandhorsebeansgreen
423 Stringbeans
426 Carrotsandturnips
430 Okra
446 Greencorn(maize)
449 Mushroomsandtruffles
459 Chicoryroots
461 Locustbeans(carobs)
463 Othervegetablesfreshnec
484 Bananascavendish
485 OtherBanana
486 Bananas
487 Plantains
488 CookingBananas
489 Plantainsandcookingbananas
490 Oranges
495 Tangerinesmandarinsclementines
497 Lemonsandlimes
507 Pomelosandgrapefruits
512 Othercitrusfruitnec
515 Apples
521 Pears
523 Quinces
526 Apricots
530 Sourcherries
531 Cherries
534 Peachesandnectarines
536 Plumsandsloes
541 Otherstonefruits
542 Otherpomefruits
544 Strawberries
547 Raspberries
549 Gooseberries
550 Currants
552 Blueberries
554 Cranberries
558 Otherberriesandfruitsofthegenusvacciniumnec
560 Grapes
564 Wine
567 Watermelons
568 Cantaloupesandothermelons
569 Figs
571 Mangoesguavasandmangosteens
572 Avocados
574 Pineapples
577 Dates
587 Persimmons
591 Cashewapple
592 Kiwifruit
600 Papayas
603 Othertropicalfruitsnec
619 Otherfruitsnec
656 Coffeegreen
661 Cocoabeans
667 Tealeaves
671 Matéleaves
675 Greentea(notfermented)blacktea(fermented)andpartlyfermentedteainimmediatepackingsofacontentnotexceeding3kg
677 Hopcones
687 Pepper(Piperspp)raw
689 Chilliesandpeppersdry(CapsicumsppPimentaspp)raw
692 Vanillaraw
693 Cinnamonandcinnamon-treeflowersraw
698 Cloves(wholestems)raw
702 Nutmegmacecardamomsraw
711 Anisebadiancoriandercumincarawayfennelandjuniperberriesraw
720 Gingerraw
723 Otherstimulantspiceandaromaticcropsnec
748 Peppermintspearmint
/

kpollcrop(k)
/
89  Buckwheat
176 Beansdry
181 Broadbeansandhorsebeansdry
195 Cowpeasdry
197 Pigeonpeasdry
203 Bambarabeansdry
216 Brazilnutsinshell
217 Cashewnutsinshell
220 Chestnutsinshell
221 Almondsinshell
224 Kolanuts
226 Arecanuts
236 Soyabeans
242 Groundnutsexcludingshelled
249 Coconutsinshell
254 Oilpalmfruit
256 Palmkernels
263 Karitenuts(sheanuts)
267 Sunflowerseed
270 Rapeorcolzaseed
280 Safflowerseed
289 Sesameseed
292 Mustardseed
299 Melonseed
328 Seedcottonunginned
329 Cottonseed
333 Linseed
388 Tomatoes
394 Pumpkinssquashandgourds
397 Cucumbersandgherkins
399 Eggplants(aubergines)
401 Chilliesandpeppersgreen(CapsicumsppandPimentaspp)
414 Otherbeansgreen
423 Stringbeans
430 Okra
490 Oranges
495 Tangerinesmandarinsclementines
497 Lemonsandlimes
507 Pomelosandgrapefruits
512 Othercitrusfruitnec
515 Apples
521 Pears
523 Quinces
526 Apricots
530 Sourcherries
531 Cherries
534 Peachesandnectarines
536 Plumsandsloes
544 Strawberries
547 Raspberries
549 Gooseberries
550 Currants
552 Blueberries
554 Cranberries
558 Otherberriesandfruitsofthegenusvacciniumnec
567 Watermelons
568 Cantaloupesandothermelons
569 Figs
571 Mangoesguavasandmangosteens
572 Avocados
587 Persimmons
591 Cashewapple
592 Kiwifruit
600 Papayas
656 Coffeegreen
661 Cocoabeans
689 Chilliesandpeppersdry(CapsicumsppPimentaspp)raw
692 Vanillaraw
/

cropgroup/
Cereals
RootsAndTubers
Oilcrops
SugarCrops
Pulse
Vegetables
Treenuts
Fruits
Stimulants
Spices
/

mapping_k_cropgroup(k,cropgroup)
/
89.Cereals     Buckwheat
176.Pulse       Beansdry
181.Pulse       Broadbeansandhorsebeansdry
195.Pulse       Cowpeasdry
197.Pulse       Pigeonpeasdry
203.Pulse       Bambarabeansdry
216.Treenuts        Brazilnutsinshell
217.Treenuts        Cashewnutsinshell
220.Treenuts        Chestnutsinshell
221.Treenuts        Almondsinshell
224.Treenuts        Kolanuts
226.OilCrops        Arecanuts
236.OilCrops        Soyabeans
242.OilCrops        Groundnutsexcludingshelled
249.OilCrops        Coconutsinshell
254.OilCrops        Oilpalmfruit
256.OilCrops        Palmkernels
263.OilCrops        Karitenuts(sheanuts)
267.OilCrops        Sunflowerseed
270.OilCrops        Rapeorcolzaseed
280.OilCrops        Safflowerseed
289.OilCrops        Sesameseed
292.OilCrops        Mustardseed
299.OilCrops        Melonseed
328.OilCrops        Seedcottonunginned
329.OilCrops        Cottonseed
333.OilCrops        Linseed
388.Vegetables      Tomatoes
394.Vegetables      Pumpkinssquashandgourds
397.Vegetables      Cucumbersandgherkins
399.Vegetables      Eggplants(aubergines)
401.Vegetables      Chilliesandpeppersgreen(CapsicumsppandPimentaspp)
414.Vegetables      Otherbeansgreen
423.Vegetables      Stringbeans
430.Vegetables      Okra
490.Fruits      Oranges
495.Fruits      Tangerinesmandarinsclementines
497.Fruits      Lemonsandlimes
507.Fruits      Pomelosandgrapefruits
512.Fruits      Othercitrusfruitnec
515.Fruits      Apples
521.Fruits      Pears
523.Fruits      Quinces
526.Fruits      Apricots
530.Fruits      Sourcherries
531.Fruits      Cherries
534.Fruits      Peachesandnectarines
536.Fruits      Plumsandsloes
544.Fruits      Strawberries
547.Fruits      Raspberries
549.Fruits      Gooseberries
550.Fruits      Currants
552.Fruits      Blueberries
554.Fruits      Cranberries
558.Fruits      Otherberriesandfruitsofthegenusvacciniumnec
567.Fruits      Watermelons
568.Fruits      Cantaloupesandothermelons
569.Fruits      Figs
571.Fruits      Mangoesguavasandmangosteens
572.Fruits      Avocados
587.Fruits      Persimmons
591.Fruits      Cashewapple
592.Fruits      Kiwifruit
600.Fruits      Papayas
656.Stimulants      Coffeegreen
661.Stimulants      Cocoabeans
689.Spices      Chilliesandpeppersdry(CapsicumsppPimentaspp)raw
692.Spices      Vanillaraw
702.Spices      NutmegCardamom
711.Spices      AnisSeed
15.Cereals      Wheat
27.Cereals      Rice
30.Cereals      Rice paddy (rice milled equivalent)
44.Cereals      Barley
51.Cereals      Beerofbarleymalted
56.Cereals      Maize(corn)
60.Cereals      Oilofmaize
71.Cereals      Rye
75.Cereals      Oats
79.Cereals      Millet
83.Cereals      Sorghum
92.Cereals      Quinoa
94.Cereals      Fonio
97.Cereals      Triticale
101.Cereals     Canaryseed
103.Cereals     Mixedgrain
108.Cereals     Cerealsnec
116.RootsAndTubers      Potatoes
122.RootsAndTubers      Sweetpotatoes
125.RootsAndTubers      Cassavafresh
135.RootsAndTubers      Yautia
136.RootsAndTubers      Taro
137.RootsAndTubers      Yams
149.RootsAndTubers      Ediblerootsandtuberswithhighstarchorinulincontentnecfresh
156.SugarCrops      Sugarcane
157.SugarCrops      Sugarbeet
161.SugarCrops      Othersugarcropsnec
162.SugarCrops      Rawcaneorbeetsugar(centrifugalonly)
165.SugarCrops      Molasses
187.Pulse       Peasdry
191.Pulse       Chickpeasdry
201.Pulse       Lentilsdry
205.Pulse       Vetches
210.Pulse       Lupins
211.Pulse       Otherpulsesnec
222.Treenuts        Walnutsinshell
223.Treenuts        Pistachiosinshell
225.Treenuts        Hazelnutsinshell
234.Treenuts        Othernuts(excludingwildediblenutsandgroundnuts)inshellnec
237.Oilcrops        Soyabeanoil
244.Oilcrops        Groundnutoil
252.Oilcrops        Coconutoil
257.Oilcrops        Palmoil
258.Oilcrops        Oilofpalmkernel
260.Oilcrops        Olives
261.Oilcrops        Oliveoil
265.Oilcrops        Castoroilseeds
268.Oilcrops        Sunflower-seedoilcrude
271.Oilcrops        Rapeseedorcanolaoilcrude
275.Oilcrops        Tungnuts
277.Oilcrops        Jojobaseeds
281.Oilcrops        Safflower-seedoilcrude
290.Oilcrops        Oilofsesameseed
296.Oilcrops        Poppyseed
305.Oilcrops        Tallowtreeseeds
310.Oilcrops        Kapokfruit
311.Oilcrops        Kapokseedinshell
331.Oilcrops        Cottonseedoil
334.Oilcrops        Oiloflinseed
336.Oilcrops        Hempseed
339.Oilcrops        Otheroilseedsnec
358.Vegetables      Cabbages
366.Vegetables      Artichokes
367.Vegetables      Asparagus
372.Vegetables      Lettuceandchicory
373.Vegetables      Spinach
378.Vegetables      Cassavaleaves
393.Vegetables      Cauliflowersandbroccoli
402.Vegetables      Onionsandshallotsgreen
403.Vegetables      Onionsandshallotsdry(excludingdehydrated)
406.Vegetables      Greengarlic
407.Vegetables      Leeksandotheralliaceousvegetables
417.Vegetables      Peasgreen
420.Vegetables      Broadbeansandhorsebeansgreen
426.Vegetables      Carrotsandturnips
446.Vegetables      Greencorn(maize)
449.Vegetables      Mushroomsandtruffles
459.Vegetables      Chicoryroots
461.Vegetables      Locustbeans(carobs)
463.Vegetables      Othervegetablesfreshnec
484.Fruits      Bananascavendish
485.Fruits      OtherBanana
486.Fruits      Bananas
487.Fruits      Plantains
488.Fruits      CookingBananas
489.Fruits      Plantainsandcookingbananas
541.Fruits      Otherstonefruits
542.Fruits      Otherpomefruits
560.Fruits      Grapes
564.Fruits      Wine
574.Fruits      Pineapples
577.Fruits      Dates
603.Fruits      Othertropicalfruitsnec
619.Fruits      Otherfruitsnec
667.Stimulants      Tealeaves
671.Stimulants      Matéleaves
675.Stimulants      Greentea(notfermented)blacktea(fermented)andpartlyfermentedteainimmediatepackingsofacontentnotexceeding3kg
677.Stimulants      Hopcones
687.Stimulants      Pepper(Piperspp)raw
693.Stimulants      Cinnamonandcinnamon-treeflowersraw
698.Stimulants      Cloves(wholestems)raw
720.Stimulants      Gingerraw
723.Stimulants      Otherstimulantspiceandaromaticcropsnec
748.Spices      Peppermintspearmint
/

cropname
/
Wheat
Rice
MilledRice
Barley
Beerofbarleymalted
Maizecorn
Oilofmaize
Rye
Oats
Millet
Sorghum
Buckwheat
Quinoa
Fonio
Triticale
Canaryseed
Mixedgrain
Cerealsnec
Potatoes
Sweetpotatoes
Cassavafresh
Yautia
Taro
Yams
Ediblerootsandtubers
Sugarcane
Sugarbeet
Othersugarcropsnec
Rawcaneorbeetsugar
Molasses
Beansdry
Broadbeansandhorsebeansdry
Peasdry
Chickpeasdry
Cowpeasdry
Pigeonpeasdry
Lentilsdry
Bambarabeansdry
Vetches
Lupins
Otherpulsesnec
Brazilnutsinshell
Cashewnutsinshell
Chestnutsinshell
Almondsinshell
Walnutsinshell
Pistachiosinshell
Kolanuts
Hazelnutsinshell
Arecanuts
Othernuts
Soyabeans
Soyabeanoil
Groundnutsexcludingshelled
Groundnutoil
Coconutsinshell
Coconutoil
Oilpalmfruit
Palmkernels
Palmoil
Oilofpalmkernel
Olives
Oliveoil
Karitenuts
Castoroilseeds
Sunflowerseed
Sunflower-seedoilcrude
Rapeorcolzaseed
Rapeseedorcanolaoilcrude
Tungnuts
Jojobaseeds
Safflowerseed
Safflower-seedoilcrude
Sesameseed
Oilofsesameseed
Mustardseed
Poppyseed
Melonseed
Tallowtreeseeds
Kapokfruit
Kapokseedinshell
Seedcottonunginned
Cottonseed
Cottonseedoil
Linseed
Oiloflinseed
Hempseed
Otheroilseedsnec
Cabbages
Artichokes
Asparagus
Lettuceandchicory
Spinach
Cassavaleaves
Tomatoes
Cauliflowersandbroccoli
Pumpkinssquashandgourds
Cucumbersandgherkins
Eggplants
Chilliesandpeppersgreen
Onionsandshallotsgreen
Onionsandshallotsdry
Greengarlic
Leeksandotheralliaceousvegetables
Otherbeansgreen
Peasgreen
Broadbeansandhorsebeansgreen
Stringbeans
Carrotsandturnips
Okra
Greencorn
Mushroomsandtruffles
Chicoryroots
Locustbeans
Othervegetablesfreshnec
Bananascavendish
OtherBanana
Bananas
Plantains
CookingBananas
Plantainsandcookingbananas
Oranges
Tangerinesmandarinsclementines
Lemonsandlimes
Pomelosandgrapefruits
Othercitrusfruitnec
Apples
Pears
Quinces
Apricots
Sourcherries
Cherries
Peachesandnectarines
Plumsandsloes
Otherstonefruits
Otherpomefruits
Strawberries
Raspberries
Gooseberries
Currants
Blueberries
Cranberries
Otherberriesandfruits
Grapes
Wine
Watermelons
Cantaloupesandothermelons
Figs
Mangoesguavasandmangosteens
Avocados
Pineapples
Dates
Persimmons
Cashewapple
Kiwifruit
Papayas
Othertropicalfruitsnec
Otherfruitsnec
Coffeegreen
Cocoabeans
Tealeaves
Mateleaves
Greentea
Hopcones
Pepper
Chilliesandpeppersdry
Vanillaraw
Cinnamonandcinnamon-treeflowersraw
Cloves
Nutmegmacecardamomsraw
Anisebadiancoriandercumincarawayfennelandjuniperberriesraw
Gingerraw
Otherstimulantspiceandaromaticcropsnec
Peppermintspearmint
/

mapping_k_cropname(k,cropname)
/
15.Wheat
27.Rice
30.MilledRice
44.Barley
51.Beerofbarleymalted
56.Maizecorn
60.Oilofmaize
71.Rye
75.Oats
79.Millet
83.Sorghum
89.Buckwheat
92.Quinoa
94.Fonio
97.Triticale
101.Canaryseed
103.Mixedgrain
108.Cerealsnec
116.Potatoes
122.Sweetpotatoes
125.Cassavafresh
135.Yautia
136.Taro
137.Yams
149.Ediblerootsandtubers
156.Sugarcane
157.Sugarbeet
161.Othersugarcropsnec
162.Rawcaneorbeetsugar
165.Molasses
176.Beansdry
181.Broadbeansandhorsebeansdry
187.Peasdry
191.Chickpeasdry
195.Cowpeasdry
197.Pigeonpeasdry
201.Lentilsdry
203.Bambarabeansdry
205.Vetches
210.Lupins
211.Otherpulsesnec
216.Brazilnutsinshell
217.Cashewnutsinshell
220.Chestnutsinshell
221.Almondsinshell
222.Walnutsinshell
223.Pistachiosinshell
224.Kolanuts
225.Hazelnutsinshell
226.Arecanuts
234.Othernuts
236.Soyabeans
237.Soyabeanoil
242.Groundnutsexcludingshelled
244.Groundnutoil
249.Coconutsinshell
252.Coconutoil
254.Oilpalmfruit
256.Palmkernels
257.Palmoil
258.Oilofpalmkernel
260.Olives
261.Oliveoil
263.Karitenuts
265.Castoroilseeds
267.Sunflowerseed
268.Sunflower-seedoilcrude
270.Rapeorcolzaseed
271.Rapeseedorcanolaoilcrude
275.Tungnuts
277.Jojobaseeds
280.Safflowerseed
281.Safflower-seedoilcrude
289.Sesameseed
290.Oilofsesameseed
292.Mustardseed
296.Poppyseed
299.Melonseed
305.Tallowtreeseeds
310.Kapokfruit
311.Kapokseedinshell
328.Seedcottonunginned
329.Cottonseed
331.Cottonseedoil
333.Linseed
334.Oiloflinseed
336.Hempseed
339.Otheroilseedsnec
358.Cabbages
366.Artichokes
367.Asparagus
372.Lettuceandchicory
373.Spinach
378.Cassavaleaves
388.Tomatoes
393.Cauliflowersandbroccoli
394.Pumpkinssquashandgourds
397.Cucumbersandgherkins
399.Eggplants
401.Chilliesandpeppersgreen
402.Onionsandshallotsgreen
403.Onionsandshallotsdry
406.Greengarlic
407.Leeksandotheralliaceousvegetables
414.Otherbeansgreen
417.Peasgreen
420.Broadbeansandhorsebeansgreen
423.Stringbeans
426.Carrotsandturnips
430.Okra
446.Greencorn
449.Mushroomsandtruffles
459.Chicoryroots
461.Locustbeans
463.Othervegetablesfreshnec
484.Bananascavendish
485.OtherBanana
486.Bananas
487.Plantains
488.CookingBananas
489.Plantainsandcookingbananas
490.Oranges
495.Tangerinesmandarinsclementines
497.Lemonsandlimes
507.Pomelosandgrapefruits
512.Othercitrusfruitnec
515.Apples
521.Pears
523.Quinces
526.Apricots
530.Sourcherries
531.Cherries
534.Peachesandnectarines
536.Plumsandsloes
541.Otherstonefruits
542.Otherpomefruits
544.Strawberries
547.Raspberries
549.Gooseberries
550.Currants
552.Blueberries
554.Cranberries
558.Otherberriesandfruits
560.Grapes
564.Wine
567.Watermelons
568.Cantaloupesandothermelons
569.Figs
571.Mangoesguavasandmangosteens
572.Avocados
574.Pineapples
577.Dates
587.Persimmons
591.Cashewapple
592.Kiwifruit
600.Papayas
603.Othertropicalfruitsnec
619.Otherfruitsnec
656.Coffeegreen
661.Cocoabeans
667.Tealeaves
671.Mateleaves
675.Greentea
677.Hopcones
687.Pepper
689.Chilliesandpeppersdry
692.Vanillaraw
693.Cinnamonandcinnamon-treeflowersraw
698.Cloves
702.Nutmegmacecardamomsraw
711.Anisebadiancoriandercumincarawayfennelandjuniperberriesraw
720.Gingerraw
723.Otherstimulantspiceandaromaticcropsnec
748.Peppermintspearmint
*  
/

ediblecrop(k) those crops included in chaplin-kramer et al 2014
/
15  Wheat
27  Rice
30  Rice paddy (rice milled equivalent)
44  Barley
*51  Beerofbarleymalted
56  Maize(corn)
71  Rye
75  Oats
79  Millet
83  Sorghum
89  Buckwheat
92  Quinoa
97  Triticale
116 Potatoes
122 Sweetpotatoes
125 Cassavafresh
135 Yautia
136 Taro
137 Yams
* add sugar crops
156
157

176 Beansdry
181 Broadbeansandhorsebeansdry
187 Peasdry
191 Chickpeasdry
195 Cowpeasdry
197 Pigeonpeasdry
201 Lentilsdry
203 Bambarabeansdry
210 Lupins
211 Otherpulsesnec
216 Brazilnutsinshell
217 Cashewnutsinshell
220 Chestnutsinshell
221 Almondsinshell
222 Walnutsinshell
223 Pistachiosinshell
* not included in Chaplin-Kramer et al.
*224 Kolanuts
225 Hazelnutsinshell
* not included in Chaplin-Kramer et al.
*226 Arecanuts
234 Othernuts(excludingwildediblenutsandgroundnuts)inshellnec
236 Soyabeans
237 Soyabeanoil
242 Groundnutsexcludingshelled
244 Groundnutoil
249 Coconutsinshell
252 Coconutoil
254 Oilpalmfruit
256 Palmkernels
257 Palmoil
258 Oilofpalmkernel
260 Olives
261 Oliveoil
263 Karitenuts(sheanuts)
267 Sunflowerseed
268 Sunflower-seedoilcrude
270 Rapeorcolzaseed
271 Rapeseedorcanolaoilcrude
280 Safflowerseed
281 Safflower-seedoilcrude
289 Sesameseed
292 Mustardseed
296 Poppyseed
299 Melonseed
* not included in Chaplin-Kramer et al.
*328 Seedcottonunginned
*329 Cottonseed
*333 Linseed
358 Cabbages
366 Artichokes
367 Asparagus
372 Lettuceandchicory
373 Spinach
388 Tomatoes
393 Cauliflowersandbroccoli
394 Pumpkinssquashandgourds
397 Cucumbersandgherkins
399 Eggplants(aubergines)
401 Chilliesandpeppersgreen(CapsicumsppandPimentaspp)
402 Onionsandshallotsgreen
403 Onionsandshallotsdry(excludingdehydrated)
406 Greengarlic
414 Otherbeansgreen
417 Peasgreen
420 Broadbeansandhorsebeansgreen
423 Stringbeans
426 Carrotsandturnips
430 Okra
446 Greencorn(maize)
449 Mushroomsandtruffles
459 Chicoryroots
461 Locustbeans(carobs)
484 Bananascavendish
485 OtherBanana
486 Bananas
487 Plantains
488 CookingBananas
489 Plantains Cooking
490 Oranges
495 Tangerinesmandarinsclementines
497 Lemonsandlimes
507 Pomelosandgrapefruits
512 Othercitrusfruitnec
515 Apples
521 Pears
523 Quinces
526 Apricots
530 Sourcherries
531 Cherries
534 Peachesandnectarines
536 Plumsandsloes
544 Strawberries
547 Raspberries
549 Gooseberries
550 Currants
552 Blueberries
554 Cranberries
558 Otherberriesandfruitsofthegenusvacciniumnec
560 Grapes
567 Watermelons
568 Cantaloupesandothermelons
569 Figs
571 Mangoesguavasandmangosteens
572 Avocados
574 Pineapples
577 Dates
587 Persimmons
591 Cashewapple
592 Kiwifruit
600 Papayas
603 Othertropicalfruitsnec
619 Otherfruitsnec
656 Coffeegreen
661 Cocoabeans
687 Pepper(Piperspp)raw
689 Chilliesandpeppersdry(CapsicumsppPimentaspp)raw
692 Vanillaraw
693 Cinnamonandcinnamon-treeflowersraw
698 Cloves(wholestems)raw
702 Nutmegmacecardamomsraw
711 Anisebadiancoriandercumincarawayfennelandjuniperberriesraw
720 Gingerraw
748 Peppermintspearmint
/

notincluded(k)
;

notincluded(k)$(not ediblecrop(k)) = YES;